# Generated by Django 4.2.5 on 2023-09-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
